blueprint:
  name: Ventilatie met logging en override
  description: >
    Regelt de ventilatie proportioneel tussen 0-100% op basis van binnenluchtvochtigheid,
    buitenluchtvochtigheid en PM2.5-waarde. Logging wordt geschreven naar een input_text helper.
    Ventilatie wordt uitgeschakeld als het verschil tussen binnen- en buitenluchtvochtigheid kleiner is dan een instelbare drempel.
    Een override-knop kan de ventilatie tijdelijk op 80% zetten.
    V 28-09-2025 2.1: Correctie in berekening buiten_factor.
  domain: automation
  input:
    indoor_humidity_sensor:
      name: Binnenluchtvochtigheidssensor
      selector:
        entity:
          domain: sensor
    outdoor_humidity_sensor:
      name: Buitenluchtvochtigheidssensor
      selector:
        entity:
          domain: sensor
    pm25_sensor:
      name: PM2.5 sensor
      selector:
        entity:
          domain: sensor
    ventilation_entity:
      name: Ventilatie-entiteit (light)
      selector:
        entity:
          domain: light
    log_sensor:
      name: Logging helper (input_text)
      selector:
        entity:
          domain: input_text
    min_indoor_humidity:
      name: Minimale binnenluchtvochtigheid
      default: 50
      selector:
        number:
          min: 30
          max: 80
          unit_of_measurement: "%"
          mode: slider
    max_outdoor_humidity:
      name: Maximale buitenluchtvochtigheid
      default: 80
      selector:
        number:
          min: 50
          max: 100
          unit_of_measurement: "%"
          mode: slider
    pm25_threshold:
      name: PM2.5 drempelwaarde
      default: 100
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: "µg/m³"
          mode: slider
    humidity_diff_threshold:
      name: Minimale verschil binnen/buiten vochtigheid voor ventilatie
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "%"
          mode: slider
    override_switch:
      name: Override schakelaar
      selector:
        entity:
          domain: input_boolean
    override_duration:
      name: Override duur (minuten)
      default: 15
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "min"
          mode: slider

trigger:
  - platform: state
    entity_id: !input indoor_humidity_sensor
  - platform: state
    entity_id: !input outdoor_humidity_sensor
  - platform: state
    entity_id: !input pm25_sensor
  - platform: state
    entity_id: !input override_switch
    to: "on"

condition: []

action:
  - variables:
      binnen_sensor: !input indoor_humidity_sensor
      buiten_sensor: !input outdoor_humidity_sensor
      pm25_sensor_id: !input pm25_sensor
      binnen: "{{ states(binnen_sensor) | float }}"
      buiten: "{{ states(buiten_sensor) | float }}"
      pm25: "{{ states(pm25_sensor_id) | float }}"
      min_vocht: !input min_indoor_humidity
      max_buiten: !input max_outdoor_humidity
      pm_drempel: !input pm25_threshold
      verschil_drempel: !input humidity_diff_threshold
      override_switch: !input override_switch
      override_duur: !input override_duration
      override_actief: "{{ is_state(override_switch, 'on') }}"
      vocht_schaal: >
        {% if binnen < min_vocht %}
          0
        {% else %}
          {{ ((binnen - min_vocht) / (80 - min_vocht) * 60) }}
        {% endif %}
      buiten_factor: >
        {% if buiten > max_buiten %}
          0.5
        {% elif buiten > (max_buiten - 20) %}
          0.7
        {% else %}
          1.0
        {% endif %}
      boost_pm: >
        {% if pm25 < 10 %}
          0
        {% else %}
          {{ (pm25 / pm_drempel * 40) }}
        {% endif %}
      totaal: >
        {% set totaal = (vocht_schaal * buiten_factor) + boost_pm %}
        {{ [totaal, 100] | min | round(0) }}
  verschil: "{{ (binnen - buiten) | abs | round(1) }}"
  logbericht: "Override: {{ override_actief }}, Binnen: {{ binnen }}%, Buiten: {{ buiten }}%, Verschil: {{ verschil }}%, PM2.5: {{ pm25 }} µg/m³, Vocht schaal: {{ vocht_schaal | round(1) }}, Buiten factor: {{ buiten_factor }}, PM boost: {{ boost_pm | round(1) }}, Ventilatie: {{ totaal }}%"
  - service: input_text.set_value
    data:
      entity_id: !input log_sensor
      value: "binnen={{ binnen }}, buiten={{ buiten }}, pm25={{ pm25 }}, verschil={{ verschil }}, totaal={{ totaal }}"
  - service: input_text.set_value
    data:
      entity_id: !input log_sensor
      value: "{{ logbericht }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ override_actief }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input ventilation_entity
            data:
              brightness_pct: 80
          - delay:
              minutes: !input override_duration
          - service: input_boolean.turn_off
            target:
              entity_id: !input override_switch
      - conditions:
          - condition: template
            value_template: "{{ verschil < verschil_drempel }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input ventilation_entity
      - conditions: []
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input ventilation_entity
            data:
              brightness_pct: "{{ totaal }}"
mode: single
